* Firmware
This repository contains source code for the firmware and drivers
for the STM32WB55 microcontroller.

** Directory Structure
- drivers: Contains code to drive specific peripherals, devices, and interfaces
- include: Contains header files that define structures and and
  various locations in memory to configure the chip
- src: Contains the firmware source for the smartwatch

** How To Build
First, you will need an ARM cross compiler. Please follow the
instructions [[https://github.com/Field-Programmable-Smartwatch/compiler][here]] to build your own cross compiler.

#+BEGIN_SRC
make
#+END_SRC

This command will build all the fpsw binary and output it as
fpsw.bin

Please note that by default it will look for the cross compiler binary
in the path determined by CROSS_PATH which is in the example
Makefile.

** How to Flash the firmware to the smartwatch
Flip the boot mode enable switch to the on position and reset the
device. Then connect the device to the computer via USB and run the
following command:

#+BEGIN_SRC
make flash-fpsw
#+END_SRC
